config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end

  get 'search', to: 'search#search'

  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :author, :body, :presence => true
end

app/models/post.rb
require 'elasticsearch/model'

class Post < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  validates :title, :body, :author, :presence => true
  has_many :comments

  def self.search(query)
    # __elasticsearch__.search(
    #     { "query": { "multi_match": { "query": query, "fields": ["title", "body"] }}}
    # )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create 
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)

    if @post.comments.create(comment_params)
      redirect_to @post,
                  notice: 'Comment was successfully added.'

    else
      redirect_to @post,
                  alert: 'Error creating comment.' + 
                  @comment.errors.full_messages.to_sentence
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    @comment.destroy

    redirect_to @post, notice: 'your comment was successfully deleted!'
  end
    

  private 

    def comment_params
      params.require(:comment).permit(:author, :body, :emails)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :author)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @posts = []
    else
      @posts = Post.search(params[:q])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def friendly_date(d)
    d.strftime("%A %d %B, %Y %H:%M:%S")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.author %> (<em><%= comment.emails %></em>) said:</p>

<blockquote>
  <%= comment.body %><br>
  <small><em><%= friendly_date comment.created_at %></em></small><br />
  <%= link_to 'Destroy', [comment.post, comment], method: :delete, data: { confirm: 'Delete comment?' } %>
</blockquote>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="ceeBlogApp">
<head>
  <title>CeeMion's Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <!--<div class="navbar-fixed">-->
      <!--<nav>-->
        <!--<div class="wrapper">-->
        <!--</div>-->
      <!--</nav>-->
    <!--</div>-->

    <div class="navbar-fixed">
      <nav class="row">
        <div class="nav-wrapper col m8 center-align">
          <a href="#!" class="brand-logo right">Logo</a>
          <ul class="hide-on-med-and-down">
            <li><a href="sass.html">Sass</a></li>
            <li><a href="badges.html">Components</a></li>
            <li class="active"><a href="collapsible.html">JavaScript</a></li>
          </ul>
        </div>
      </nav>
    </div>

    <div class="container">
    <header>
      <h1>CeeMion's Repository of Wealth</h1>
      <p>Today is <strong><%= friendly_date Time.now %></strong></p>
    </header>

    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  .field
    = f.label :title
    = f.text_field :title
    - if @post.errors[:title]
      = @post.errors.full_messages[0]

  .field
    = f.label :author
    = f.text_field :author
    - if @post.errors[:title]
      = @post.errors.full_messages[1]

  .field
    = f.label :body
    = f.text_area :body
    - if @post.errors[:title]
      = @post.errors.full_messages[2]

  .actions
    = f.submit

app/views/posts/edit.html.haml
%h1 Editing Post
= render 'form'
= link_to 'Show', @post
|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%div{"ng-controller" => "blogCtrl"}
  = link_to 'Create a New Post', new_post_path
  = link_to 'Search', search_path
  %br/
  %p Message from Angular controller
  %p{"ng-bind" => "test"}
  %br/
  %div
  - @posts.each do |post|
    %h2= link_to post.title, post
    %span
      Posted by #{post.author} on
      %i= friendly_date post.created_at
    %p= post.body
    %p
      = link_to 'Edit', edit_post_path(post)
      = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
    %br/
  %br/

app/views/posts/new.html.haml
%h1 Create a New Post
= render 'form'
= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%h1= @post.title

%p= @post.body

= link_to 'Edit', edit_post_path(@post)
|
= link_to 'Back Home', posts_path
|
= link_to 'Bach to Search', search_path

%h3 Comments

= render @post.comments

%h4 New Comment
= form_for [@post, @post.comments.build] do |f|
  .field
    = f.label :author
    = f.text_field :author

  .field
    = f.label :emails
    = f.text_field :emails

  .field
    = f.label :body
    = f.text_area :body

  .actions
    = f.submit

app/views/search/search.html.haml
%h2 Another era in Elasticsearch
= link_to 'Go back', posts_path
.search-form
  = form_for search_path, method: :get do |s|
    %p
      = s.label 'Search For'
      = text_field_tag :q, params[:q]
      = submit_tag 'Go', name: nil
  %h4 Search Results
  - if @posts.empty? and !params[:q].nil?
    %p No results found for <strong>"#{params[:q]}"</strong>.
  - else
    %ul
      - @posts.each do |result|
        %ul= result.title
        = link_to 'View Post', controller: 'posts', action: 'show', id: result._id
        %br